### PR TITLE
Dashboard Screen Development

### PR DESCRIPTION
**Pull request by gab-stargazer**
I develop Dashboard Screen with mockup data following the mockup, but i think we need to make some adjustment on fontsize, etc. I also notice that the API response for Popular Movie doesn't return Duration of the movie.

Change:
1. Dashboard Screen
2. Horizontal Movie Item
3. Vertical Movie Item
4. Section Separator
5. Added Flow Layout Dependencies from Accompanist for Movie Categories.
6. Added temporary Movie data class for preview purposes.

### CODE REVIEW

**Comment by Dawid-Witkowski** [comment]
Exporting the strings instead of hard-coding them might help us later (I've noticed some hard-coded values in descriptors etc.)

**Comment by gab-stargazer** [comment]
Are you sure? I checked it again after ur comment, and i think i already extract all the string

**Comment by Dawid-Witkowski** [comment]
Nvm, my sleepy ass checked it commit-by-commit, not file-by-file, lgtm

**Comment by Dawid-Witkowski** [comment]
Also, why is PopularMovies a list of hard-coded Movies? aren't we supposed to get those values from an API of some sort? 🤔

**Comment by gab-stargazer** [comment]
Yes, i made it for the preview purposes since the data layer hasn't been made. It'll be replaced by the data coming from the API when the data layer is done

**Review by Dawid-Witkowski — APPROVED** [review]

**Pull request merged**
